### ISSUE TITLE
Borrar

### ISSUE THREAD

**Issue by felipecorral** [totiberal/Actividade3b#1]
Borra el import android. App. Suport. Fragment 
Y el de debajo tb

**Comment by totiberal** [comment]
No se lo puedo borrar, lo necesito para crear el fragment manager no?

**Comment by totiberal** [comment]
O fallo estaba na clase secundaria.

public class Dialogos extends android.app.DialogFragment {

 cambieille o extends por:

public class Dialogos extends android.support.v4.app.DialogFragment {

e xa funciona, non sei o motivo pero vai ben

**Comment by felipecorral** [comment]
Ya sabes, si funciona, "no le toques".
